config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'
  get '/tasks', to: 'tasks#index'
  get '/tasks/new', to: 'tasks#new'
  delete '/tasks/:id', to: 'tasks#destroy', as: :destroy
  get '/tasks/:id', to: 'tasks#show', as: :task
  post '/tasks', to: 'tasks#create'
  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch '/tasks/:id', to: 'tasks#update'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to root_path
  end
  
  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to root_path
  end




  private

  def task_params
    params.require(:task).permit('title','details','completed')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1 class="mb-5">Edit Task</h1>

<div class="form-container">
  <%= simple_form_for(@task) do |f| %>
    <%= f.input :title %>
    <%= f.input :details %>
    <%= f.input :completed %>
    <%= f.submit class: "btn btn-primary"%>
  <% end %>
</div>

app/views/tasks/index.html.erb
<h1 class="mb-5">My tasks</h1>

<ul class="list-unstyled pl-4">
  <% @tasks.each do |task| %>
  <li>
    <input type="checkbox" <%= "checked" if task.completed %>>
    <%= link_to task.title, task_path(id: task.id) %>
    <%= link_to raw('<i class="fa fa-trash" aria-hidden="true"></i>'), destroy_path(task), method: :delete, data: { confirm: "Are you sure?" } %>
  </li>
  <% end %>
</ul>

<%= link_to "Create task", tasks_new_path, class: "btn btn-primary mx-4" %>

app/views/tasks/new.html.erb
<h1 class="mb-5">Create New Task</h1>

<div class="form-container mx-4">
  <%= simple_form_for(@task) do |f| %>
    <%= f.input :title %>
    <%= f.input :details %>
    <%= f.hidden_field :completed%>
    <%= f.submit class: "btn btn-primary"%>
  <% end %>
</div>

<div class="my-4">
  <%= link_to "Back", tasks_path, class: "btn btn-primary mx-4" %>
</div>

app/views/tasks/show.html.erb
<h1 class="mb-5"><%= @task.title %></h1>

<section class="description-box pl-4">
  <p><%= @task.details %></li></p>
</section>

<section class="complete-task-box pl-4">
  <input type="checkbox" disabled <%= "checked" if @task.completed %> > 
  <p>The task is completed</p>
</section>

<footer>
  <%= link_to "Edit task", edit_path, class: "btn btn-primary mx-4"%>
  <%= link_to "Back to list", tasks_path, class: "btn btn-primary mx-4" %>
</footer>